VIA_ENABLE = yes
VIAL_ENABLE = yes
<<<<<<< HEAD
RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes
LTO_ENABLE = yes

CONSOLE_ENABLE = no

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
=======

VIALRGB_ENABLE = yes
>>>>>>> upstream/vial
