// Copyright 2022 Diego Palacios (@diepala)
// SPDX-License-Identifier: GPL-2.0

#include QMK_KEYBOARD_H

#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_LAYER0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, MO(6), MO(1), KC_SPC, KC_BSPC, MO(2), TO(3)),

    [_LAYER1] = LAYOUT_split_3x5_3(LCA(KC_TAB), KC_TAB, KC_TAB, KC_TAB, KC_TAB, KC_BSPC, KC_7, KC_8, KC_9, KC_0, OSM(MOD_LGUI), OSM(MOD_LALT), OSM(MOD_LCTL), OSM(MOD_LSFT), KC_ESC, KC_DEL, KC_4, KC_5, KC_6, KC_DOT, LCTL(KC_UP), KC_GRV, KC_GRV, KC_GRV, CW_TOGG, KC_ENT, KC_1, KC_2, KC_3, KC_COMM, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SPC, KC_TRNS),

    [_LAYER2] = LAYOUT_split_3x5_3(KC_GRV, KC_TILD, KC_LBRC, KC_RBRC, KC_TAB, KC_BSPC, KC_QUOT, KC_DQUO, KC_PIPE, KC_QUES, KC_UNDS, KC_MINS, KC_PLUS, KC_EQL, KC_ESC, KC_DEL, OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_LT, KC_GT, KC_LPRN, KC_RPRN, CW_TOGG, KC_ENT, KC_LCBR, KC_RCBR, KC_BSLS, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_LAYER3] = LAYOUT_split_3x5_3(KC_NO, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_NO, TO(4), TO(5), KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_NO, OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_LAYER4] = LAYOUT_split_3x5_3(KC_NO, KC_WH_L, KC_MS_U, KC_WH_R, KC_WH_U, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_NO, KC_BTN1, KC_BTN3, KC_BTN2, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_LAYER5] = LAYOUT_split_3x5_3(KC_NO, KC_F7, KC_F8, KC_F9, KC_F12, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_NO, KC_F1, KC_F2, KC_F3, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_LAYER6] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_BSPC, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_ESC, KC_DEL, KC_MPRV, KC_MPLY, KC_MNXT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_ENT, KC_NO, RGB_VAD, RGB_VAI, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)

};
